### ISSUE TITLE
Cannot download plugin in VSCode

### ISSUE THREAD

**Issue by kinxiel** [bram209/leptos-language-server#3]
Tried to download it in VSCode but error says there is no release version.

Not a lot of description about the plugin, does it do the same thing as leptos fmt?

**Comment by bram209** [comment]
Yes, currently it only does formatting.
For now, you have to install it as a pre-release:
https://devblogs.microsoft.com/python/wp-content/uploads/sites/12/2022/03/IntallPreReleaseButton2.png][pre-release
