### ISSUE TITLE
Server becomes unresponsive and crashes upon formatting request in NeoVim

### ISSUE THREAD

**Issue by shakesbeare** [bram209/leptos-language-server#4]
Hey, not sure how actively you are maintaining either of your tools (leptos-language-server and leptosfmt), but I've been working on a project with leptos recently and have been truly suffering not having a formatter to work with. So I've been trying to get your stuff to work. 

I first tried to make leptosfmt work with null-ls, but it didn't seem to play nice. Requiring either a buffer reload or not doing anything at all. So, then I tried to set up leptos-language-server. The good news is that it seems to have been setup and is interacting with NeoVim okay. The bad news is that it doesn't seem to want to do anything. 

Upon executing a format request, the server times out and closes itself. I have tried extending the timeout duration to as far as 100 seconds and it still occurs. The complexity of the file doesn't seem to affect it. The server does seem to be receiving messages because this does not occur on buffers that don't have the view!{} macro, indicating that it's at least trying to do something. 

I'm attaching my little config for the setup. I'm not sure how familiar you are with the NeoVim LSP api (I know I'm not), but maybe some of the information might help track something down.

```
vim.api.nvim_create_autocmd("BufEnter", {
    pattern = "*.rs",
    callback = function()
        vim.lsp.start({
            name = "leptos-lsp",
            cmd = { "leptos-language-server" },
            filetypes = { "rust" },
            root_dir = vim.fs.dirname(vim.fs.find({ 'Cargo.toml' }, { upward = true })[1])
        })
        vim.lsp.buf_attach_client(0, 1)
    end
})
```

The client starts up successfully and attaches to the buffer. When executing a formatting request with `vim.lsp.buf.format()`, the client times out and ends.

Alternatively, if you happen to have a solution involving the raw leptosfmt, I'd be more than happy to try it out.

**Comment by bram209** [comment]
> I first tried to make leptosfmt work with null-ls, but it didn't seem to play nice. Requiring either a buffer reload or not doing anything at all

You could try this configuration: https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1590/files
